# Generated by Django 3.2 on 2025-01-09 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0015_auto_20250109_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='お名前には日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', max_length=150, validators=[django.core.validators.RegexValidator(message='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', max_length=150, validators=[django.core.validators.RegexValidator(message='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザーネームは既に使用されています。'}, help_text='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザーネームには日本語、アルファベット、数字、記号(@, ., +, -, _)のみ使用できます。', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\uFF00-\\uFFEFa-zA-Z0-9@.+-_]+$')], verbose_name='username'),
        ),
    ]
